name: Run Job on Merge
on:
  push:
    branches:
      - main

jobs:
  run_on_merge:
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: 43786
      JOB_ID: 521772

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: pip install dbtc==0.8.0

      - name: Run Merge Job
        run: |
          run=$(dbtc trigger-job \
              --job-id=$JOB_ID \
              --payload='{"cause": "Merging code to main"}')
          echo "RUN_ID=$(echo $run | jq '.data.id')" >> $GITHUB_ENV